export const ADMIN_NAV = [
  ["/admin", "Dashboard"],
  ["/admin/exams", "Examinations"],
  ["/admin/otr", "OTR / Candidates"],
  ["/admin/registrations", "Exam Registration"],
  ["/admin/centres", "Centre Management"],
  ["/admin/labs", "Labs & Capacity"],
  ["/admin/allocation", "Allocation Engine"],
  ["/admin/exceptions", "Exceptions"],
  ["/admin/passes", "Admit / Gate Pass"],
  ["/admin/gate", "Gate Entry"],
  ["/admin/verify", "Identity / Biometric"],
  ["/admin/attendance", "Attendance"],
  ["/admin/live", "Live Monitoring"],
  ["/admin/staff", "Staff & Operators"],
  ["/admin/reports", "Reports"],
  ["/admin/notify", "Notifications"],
  ["/admin/helpdesk", "Helpdesk"],
  ["/admin/audit", "Audit Logs"],
  ["/admin/config", "System Configuration"],
  ["/admin/users", "Admin Users / Roles"],
  ["/admin/health", "Backup / Health"],
];
